default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: gpa_calc
  username: postgres
  password: admin
  host: localhost

test:
  <<: *default
  database: gpa_calc_test
  username: postgres
  password: admin

production:
  <<: *default
  database: gpa_calc_production
  username: postgres
  password: admin
  host: localhost
  port: 5432


